#엔드포인트를 사용하려면 다음 2가지 과정이 모두 필요하다.
#1. 엔드포인트 활성화
#2. 엔드포인트 노출
#엔드포인트는 대부분 기본으로 활성화 되어 있다.( shutdown 제외) 노출이 되어 있지 않을 뿐이다.
#특정 엔드포인트를 활성화 하려면 management.endpoint.{엔드포인트명}.enabled=true 를 적용하면 된다.
#include: "*" 모든 엔드포인트 노출
management:
  endpoint:
    shutdown:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"